recipe: default.v1
language: pt-BR
assistant_id: 20230405-114328-tranquil-mustard

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: gemini_llm # Model group ID
    flow_retrieval:
      embeddings:
        model_group: gemini_embeddings_model 

policies:
  - name: rasa.core.policies.flow_policy.FlowPolicy